
import asyncio
import httpx
import json

API_URL = "http://127.0.0.1:8000/api/v1/quizzes/"

# Mock payload based on CreateQuiz.jsx
payload = {
    "title": "Test Quiz",
    "description": "Generated by repro script",
    "is_public": True,
    "questions": [
        {
            "text": "What is 2+2?",
            "question_type": "multiple_choice",
            "points": 10,
            "time_limit": 20,
            "choices": [
                {"text": "3", "is_correct": False},
                {"text": "4", "is_correct": True},
                {"text": "5", "is_correct": False},
                {"text": "6", "is_correct": False}
            ]
        }
    ]
}

async def test_create_quiz():
    async with httpx.AsyncClient() as client:
        # We need to be authenticated. 
        # For reproduction, we assume the backend might be checking auth.
        # But we can try hitting it. If 401, we know it's auth.
        # If 400, it's our target bug.
        
        # Note: The backend endpoint requires 'current_user'.
        # We might need to login first. 
        # But let's try without auth first to see if we get 401 (which proves endpoint is reachable).
        
        print(f"Sending payload: {json.dumps(payload, indent=2)}")
        response = await client.post(API_URL, json=payload)
        print(f"Status: {response.status_code}")
        print(f"Response: {response.text}")

if __name__ == "__main__":
    asyncio.run(test_create_quiz())
